version: 2

references:

  ## Workspace

  workspace: &workspace
               ~/workspace

  ## Cache

  cache_key: &cache_key
    key: cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle
        - ~/.m2

  ## Docker image configurations

  jdk_config: &jdk_config
    working_directory: *workspace
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.caching=false

jobs:
  build:
    <<: *jdk_config
    steps:
      - checkout

      - *restore_cache
      - run:
          name: Download dependencies
          command: ./gradlew dependencies --refresh-dependencies --stacktrace
      - *save_cache

      - run: ./gradlew assemble --stacktrace
      
      - store_artifacts:
          path: ./build/libs
          destination: wars

  ktlint:
    <<: *jdk_config
    steps:
      - checkout
      - run: ./gradlew ktlint --stacktrace

  test:
    <<: *jdk_config
    steps:
      - checkout
      - *restore_cache

      - run: ./gradlew test --refresh-dependencies --stacktrace
      - run:
          name: Save test results 
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ./build/reports/tests/test
          destination: tests

  publish:
    <<: *jdk_config
    steps:
      - checkout
      - *restore_cache

      - run:
          name: Uploading to Nexus Sonatype
          command: ./gradlew publish -PLOCAL_UPLOAD=false --stacktrace

workflows:
  version: 2
  commit:
    jobs:
      - ktlint
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test